version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8001
    ports:
      - 8001:8001
    volumes:
      - media_file
    depends_on:
      - db

  db:
    image: postgres:16
    env_file:
      - .db.env
volumes:
  media_file:
