version: '3'

services:
  web:
    build: .
    command: gunicorn KUN_UZ.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - media_file
    depends_on:
      - db

  db:
    image: postgres:16
    env_file:
      - .prod.db.env
  nginx:
    build: ./nginx
    depends_on:
      - web

volumes:
  media_file:
