# Generated by Django 5.0.2 on 2024-02-18 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_categories_slug_alter_news_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='name',
        ),
    ]
